Final exam Assignment 3 Submission

In [69]:
!pip install pyinputplus

Requirement already satisfied: pyinputplus in /usr/local/lib/python3.12/dist-packages (0.2.12)
Requirement already satisfied: pysimplevalidate>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from pyinputplus) (0.2.12)
Requirement already satisfied: stdiomask>=0.0.3 in /usr/local/lib/python3.12/dist-packages (from pyinputplus) (0.0.6)

In [70]:
import pandas as pd
import pyinputplus as pyip
import os

Here i imported pandas for data habdling, pyinputplus for input validity, and os to check if the file exists.

In [71]:
def load_data():
    try:
        df = pd.read_csv("budget.csv")
        print("Data loaded successfully.")
    except FileNotFoundError:
        df = pd.DataFrame(columns=['date', 'description', 'type', 'amount'])
        print("No existing file found. Starting fresh.")
    return df

In [72]:
df = load_data()
df

Data loaded successfully.

         date description     type  amount
0  2002-07-14        okay   income  1222.0
1  2003-09-19        okay  expense   200.0
2   2005-8-11     sallary   income  1000.0
3  2003-08-11     sallary   income  2000.0
4  2004-05-16     grocery  expense   100.0
5  2006-09-15        home   income  1000.0

In this cell i collected my inputs for date, description, type and all.

In [73]:
def show_menu():
    print("\n1. Add Transaction")
    print("2. View All Transactions")
    print("3. View Balance")
    print("4. Save & Exit")

In [74]:
def add_transaction(df):
    date = pyip.inputStr("Enter date (YYYY-MM-DD): ")
    description = pyip.inputStr("Enter description: ")

    t_type = pyip.inputChoice(['income', 'expense'])

    amount = pyip.inputFloat("Enter amount: ", min=0.01)

    new_row = {
        "date": date,
        "description": description,
        "type": t_type,
        "amount": amount
    }

    df.loc[len(df)] = new_row

    print("Transaction added!")

    return df

In [75]:
def view_transactions(df):
    if df.empty:
        print("No transactions yet.")
    else:
        print(df)

In [76]:
def calculate_balance(df):
    income = df[df['type'] == 'income']['amount'].sum()
    expense = df[df['type'] == 'expense']['amount'].sum()
    return income - expense

In [77]:
def save_data(df):
    df.to_csv("budget.csv", index=False)
    print("Data saved successfully.")

In [91]:
def main():
    df = load_data()

    while True:
        show_menu()

        choice = pyip.inputInt("Choose option (1-4): ", min=1, max=4)

        if choice == 1:
            df = add_transaction(df)

        elif choice == 2:
            view_transactions(df)

        elif choice == 3:
            balance = calculate_balance(df)
            print(f"Current Balance: ${balance:.2f}")

        elif choice == 4:
            save_data(df)
            print("Goodbye!")
            break

In [79]:
import pandas as pd

# recreate your dataset as test data
test_df = pd.DataFrame({
    "date": [
        "2002-07-14",
        "2003-09-19",
        "2005-8-11",
        "2003-08-11",
        "2004-05-16",
        "2006-09-15"
    ],
    "description": [
        "okay",
        "okay",
        "sallary",
        "sallary",
        "grocery",
        "home"
    ],
    "type": [
        "income",
        "expense",
        "income",
        "income",
        "expense",
        "income"
    ],
    "amount": [
        1222.0,
        200.0,
        1000.0,
        2000.0,
        100.0,
        1000.0
    ]
})

# assert test for your function
assert calculate_balance(test_df) == 4922

Now in this loop, it will continuously display the menu and allows user to choose actions until they decide to save and exit.

In [80]:
main()

Data loaded successfully.

1. Add Transaction
2. View All Transactions
3. View Balance
4. Save & Exit
Choose option (1-4): 4
Data saved successfully.
Goodbye!

In [81]:
import pandas as pd

df = pd.read_csv("budget.csv")
df

         date description     type  amount
0  2002-07-14        okay   income  1222.0
1  2003-09-19        okay  expense   200.0
2   2005-8-11     sallary   income  1000.0
3  2003-08-11     sallary   income  2000.0
4  2004-05-16     grocery  expense   100.0
5  2006-09-15        home   income  1000.0

In [82]:
save_data(df)

Data saved successfully.

In [83]:
from google.colab import files
files.download("budget.csv")

In [84]:
df.to_csv("budget.csv", index=False)

In [85]:
test_df = pd.DataFrame({
    "date": ["2026-01-01", "2026-01-02"],
    "description": ["a", "b"],
    "type": ["income", "expense"],
    "amount": [1000, 200]
})

assert calculate_balance(test_df) == 800
print("Test passed")

Test passed

Here, it Shows the Test has been passed.

In [86]:
def calculate_balance(df):
    income = df[df['type'] == 'income']['amount'].sum()
    expense = df[df['type'] == 'expense']['amount'].sum()
    return income - expense


test_df = pd.DataFrame({
    "date": ["2020-01-01", "2020-01-02"],
    "description": ["test1", "test2"],
    "type": ["income", "expense"],
    "amount": [1000, 300]
})

assert calculate_balance(test_df) == 700
print("Assert test passed")

Assert test passed

In [87]:
%%writefile .gitignore
__pycache__/
*.pyc
*.pyo
*.pyd
.Python
env/
venv/
.ipynb_checkpoints
.DS_Store

Overwriting .gitignore

In [88]:
!mv gitignore .gitignore

mv: cannot stat 'gitignore': No such file or directory

In [89]:
from google.colab import files
files.download(".gitignore")

In [90]:
!ls -a

.  ..  budget.csv  .config  .gitignore	sample_data

Reflection
During this assignment i used Ai Chatgpt as a learning and support tool to help me understand and structure my persoal Budget Manager Program.

 Using Chatgpt helped me to uderstand and structure my personal budget manager program, and. also assisted me in breaking down the assigment requirement, planning the programming logic, and also developign pseudocode.